name: "Terraform CI/CD"

on:
  pull_request:
    branches:
      - main  # Ejecuta Terraform Plan cuando hay un PR a main
  push:
    branches:
      - main  # Aplica los cambios cuando se hace un push a main

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: "Authenticate with GCP"
        run: |
          echo '${{ secrets.GCP_TERRAFORM_SA_KEY }}' | gcloud auth activate-service-account --key-file=/dev/stdin
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Format"
        run: terraform fmt -check

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan -out=tfplan
        continue-on-error: false  # Ahora fallará si hay errores en plan

      - name: "Upload Terraform Plan"
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
          retention-days: 1  # Mantener el archivo solo por un día

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform-plan  # Solo ejecuta si terraform-plan fue exitoso
    if: github.ref == 'refs/heads/main'  # Solo aplica en push a main

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: "Authenticate with GCP"
        run: |
          echo '${{ secrets.GCP_TERRAFORM_SA_KEY }}' | gcloud auth activate-service-account --key-file=/dev/stdin
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Download Terraform Plan"
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: "Terraform Apply"
        run: terraform apply -auto-approve tfplan
