name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_TF_KEY }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Generate Terraform plan
        run: |
          terraform plan \
            -var="project_id=${{ secrets.TF_VAR_project_id }}" \
            -var="bucket_name=${{ secrets.TF_VAR_bucket_name }}" \
            -var="region_name=${{ secrets.TF_VAR_region_name }}"

      - name: Manual approval before applying
        uses: trstringer/manual-approval@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Terraform configuration
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.TF_VAR_project_id }}" \
            -var="bucket_name=${{ secrets.TF_VAR_bucket_name }}" \
            -var="region_name=${{ secrets.TF_VAR_region_name }}"
        if: success()